"""Reason Codes：Adaptive Policy 的可解释原因码（集中定义）。

用于：
- AdaptiveDecision.reason_codes
- Adaptive Decision Trace 展示
- 调试 / 实验 / Policy 对比
"""

# 掌握度相关
REASON_LOW_TARGET_MASTERY = "LOW_TARGET_MASTERY"
REASON_TARGET_MASTERED = "TARGET_MASTERED"
REASON_UNKNOWN_KNOWLEDGE_STATE = "UNKNOWN_KNOWLEDGE_STATE"

# 前置
REASON_LOW_PREREQUISITE_MASTERY = "LOW_PREREQUISITE_MASTERY"
REASON_PREREQUISITE_UNKNOWN = "PREREQUISITE_UNKNOWN"

# 置信度 / 能力
REASON_LOW_MASTERY_CONFIDENCE = "LOW_MASTERY_CONFIDENCE"
REASON_LOW_UNDERSTANDING_ABILITY = "LOW_UNDERSTANDING_ABILITY"

# 误解 / 时间
REASON_ACTIVE_MISCONCEPTION = "ACTIVE_MISCONCEPTION"
REASON_HIGH_REVIEW_RISK = "HIGH_REVIEW_RISK"

# 偏好 / 会话
REASON_PREFERENCE_WORKED_EXAMPLE = "PREFERENCE_WORKED_EXAMPLE"
REASON_REPEATED_REEXPLANATION = "REPEATED_REEXPLANATION"

# 数据缺失
REASON_NO_DATA = "NO_DATA"

ALL_REASON_CODES = [
    REASON_LOW_TARGET_MASTERY,
    REASON_TARGET_MASTERED,
    REASON_UNKNOWN_KNOWLEDGE_STATE,
    REASON_LOW_PREREQUISITE_MASTERY,
    REASON_PREREQUISITE_UNKNOWN,
    REASON_LOW_MASTERY_CONFIDENCE,
    REASON_LOW_UNDERSTANDING_ABILITY,
    REASON_ACTIVE_MISCONCEPTION,
    REASON_HIGH_REVIEW_RISK,
    REASON_PREFERENCE_WORKED_EXAMPLE,
    REASON_REPEATED_REEXPLANATION,
    REASON_NO_DATA,
]
